#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
set -x
for config_file in bash_profile tmux.conf vimrc; do
  # Notice that in the script dir there is no '.' prefix, but there is in home
  ln -i -s "${DIR}/${config_file}" "${HOME}/.${config_file}"
done

